---
docker-credentials: &docker-credentials
  username: ((ce-dockerhub-id))
  password: ((ce-dockerhub-token))

resource_types:
  - name: meta
    type: docker-image
    source:
      repository: swce/metadata-resource
      <<: *docker-credentials

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      <<: *docker-credentials

  - name: chromedriver-version
    type: docker-image
    source:
      repository: openstax/chromedriver-version-resource
      tag: 1.0.0
      <<: *docker-credentials

resources:
  - name: meta
    type: meta

  - name: notify-slack
    type: slack-notification
    source:
      url: ((slack-webhook-qa-stream))

  - name: selenium-base
    type: docker-image
    source:
      repository: openstax/selenium-base
      <<: *docker-credentials

  - name: selenium-chrome
    type: docker-image
    source:
      repository: openstax/selenium-chrome
      <<: *docker-credentials

  - name: selenium-chrome-debug
    type: docker-image
    source:
      repository: openstax/selenium-chrome-debug
      <<: *docker-credentials

  - name: chromedriver-latest
    type: chromedriver-version

  - name: docker-qa-images
    type: git
    source:
      uri: https://github.com/openstax/docker-qa.git
      branch: master

jobs:
  - name: build-and-publish-images
    plan:
      - get: chromedriver-latest
        trigger: true
      - get: meta
      - get: docker-qa-images
      - task: create-version-message
        file: docker-qa-images/.concourse/tasks/version-message/task.yml
      - put: notify-slack
        params:
          text_file: message-output/out.txt
      - task: generate-timestamp-tag
        file: docker-qa-images/.concourse/tasks/generate-tag/task.yml
      - put: selenium-base
        params:
          build: docker-qa-images/selenium/base
          tag_file: generated-tag/TAG
          tag_as_latest: true
      - put: selenium-chrome
        params:
          build: docker-qa-images/selenium/chrome
          tag_file: generated-tag/TAG
          tag_as_latest: true
      - put: selenium-chrome-debug
        params:
          build: docker-qa-images/selenium/chrome-debug
          tag_file: generated-tag/TAG
          tag_as_latest: true
    on_success:
      put: notify-slack
      params:
        text: ":white_check_mark: all selenium chromedriver images have been updated"
    on_failure:
      put: notify-slack
      params:
        text: ":warning: There was problem building all the selenium chromedriver images"
