---
docker-credentials: &docker-credentials
  username: ((ce-dockerhub-id))
  password: ((ce-dockerhub-token))

resource_types:
  - name: meta
    type: docker-image
    source:
      repository: swce/metadata-resource
      <<: *docker-credentials

  - name: chromedriver-version
    type: docker-image
    source:
      repository: openstax/chromedriver-version-resource
      tag: 1.0.1
      <<: *docker-credentials

resources:
  - name: meta
    type: meta

  - name: selenium-base
    type: docker-image
    source:
      repository: openstax/selenium-base
      <<: *docker-credentials

  - name: selenium-chrome
    type: docker-image
    source:
      repository: openstax/selenium-chrome
      <<: *docker-credentials

  - name: selenium-chrome-debug
    type: docker-image
    source:
      repository: openstax/selenium-chrome-debug
      <<: *docker-credentials

  - name: chromedriver-latest
    type: chromedriver-version

  - name: docker-qa-images
    type: git
    source:
      uri: https://github.com/openstax/docker-qa.git
      branch: master

  - name: selenium-base-dockerfile
    type: git
    source:
      uri: https://github.com/openstax/docker-qa.git
      branch: master
      paths:
        - selenium/base/Dockerfile

jobs:
  - name: build-and-publish-images
    plan:
      - get: chromedriver-latest
        trigger: true
      - get: selenium-base-dockerfile
        trigger: true
      - get: meta
      - get: docker-qa-images
      - task: create-version-message
        file: docker-qa-images/.concourse/tasks/version-message/task.yml
      - task: notify slack
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: curlimages/curl
              <<: *docker-credentials
          inputs:
          - name: message-output
          params:
            WEBHOOK_URL: ((slack-webhook-qa-stream))
          run:
            path: /bin/sh
            args:
            - -cxe
            - |-
              message=$(cat message-output/out.txt)
              curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${message}\"}" "$WEBHOOK_URL"
      - task: generate-timestamp-tag
        file: docker-qa-images/.concourse/tasks/generate-tag/task.yml
      - put: selenium-base
        params:
          build: docker-qa-images/selenium/base
          tag_file: generated-tag/TAG
          tag_as_latest: true
      - put: selenium-chrome
        params:
          build: docker-qa-images/selenium/chrome
          tag_file: generated-tag/TAG
          tag_as_latest: true
      - put: selenium-chrome-debug
        params:
          build: docker-qa-images/selenium/chrome-debug
          tag_file: generated-tag/TAG
          tag_as_latest: true
    on_success:
      task: notify slack
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: curlimages/curl
            <<: *docker-credentials
        params:
          WEBHOOK_URL: ((slack-webhook-qa-stream))
        run:
          path: /bin/sh
          args:
          - -cxe
          - |-
            message=":white_check_mark: all selenium chromedriver images have been updated"
            curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${message}\"}" "$WEBHOOK_URL"
    on_failure:
      task: notify slack
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: curlimages/curl
            <<: *docker-credentials
        params:
          WEBHOOK_URL: ((slack-webhook-qa-stream))
        run:
          path: /bin/sh
          args:
          - -cxe
          - |-
            message=":warning: There was problem building all the selenium chromedriver images"
            curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${message}\"}" "$WEBHOOK_URL"
